In [1]:
import torch
import numpy as np
import nmmo
from nmmo import config
from neurips2022nmmo import CompetitionConfig, TeamBasedEnv
from nmmo.io import action

class TrainConfig(CompetitionConfig):
    MAP_N = 1

env = TeamBasedEnv(TrainConfig())

100%|██████████| 1/1 [00:00<00:00, 19.19it/s]

Generating 1 maps

In [2]:
import pandas as pd

In [3]:
obs = env.reset()
obs.keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

In [7]:
obs[0].keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 'stat'])

In [9]:
pd.DataFrame(obs[0])

,0,1,2,3,4,5,6,7,stat
Entity,"{'Continuous': [[1.0, 1.0, 0.0, 3.0, 0.0, 0.0,...","{'Continuous': [[1.0, 2.0, 0.0, 3.0, 0.0, 0.0,...","{'Continuous': [[1.0, 3.0, 0.0, 3.0, 0.0, 0.0,...","{'Continuous': [[1.0, 4.0, 0.0, 3.0, 0.0, 0.0,...","{'Continuous': [[1.0, 5.0, 0.0, 3.0, 0.0, 0.0,...","{'Continuous': [[1.0, 6.0, 0.0, 3.0, 0.0, 0.0,...","{'Continuous': [[1.0, 7.0, 0.0, 3.0, 0.0, 0.0,...","{'Continuous': [[1.0, 8.0, 0.0, 3.0, 0.0, 0.0,...",NaN
Tile,"{'Continuous': [[0.0, 0.0, 9.0, 17.0], [0.0, 0...","{'Continuous': [[0.0, 0.0, 9.0, 19.0], [0.0, 0...","{'Continuous': [[0.0, 0.0, 9.0, 21.0], [0.0, 0...","{'Continuous': [[0.0, 0.0, 9.0, 23.0], [0.0, 0...","{'Continuous': [[0.0, 0.0, 9.0, 25.0], [0.0, 0...","{'Continuous': [[0.0, 0.0, 9.0, 27.0], [0.0, 0...","{'Continuous': [[0.0, 0.0, 9.0, 29.0], [0.0, 0...","{'Continuous': [[0.0, 0.0, 9.0, 31.0], [0.0, 0...",NaN
Item,"{'Continuous': [[0.0, 1.0, 0.0, 0.0, 1.0, 0.0,...","{'Continuous': [[1.0, 1.0, 0.0, 0.0, 1.0, 0.0,...","{'Continuous': [[2.0, 1.0, 0.0, 0.0, 1.0, 0.0,...","{'Continuous': [[3.0, 1.0, 0.0, 0.0, 1.0, 0.0,...","{'Continuous': [[4.0, 1.0, 0.0, 0.0, 1.0, 0.0,...","{'Continuous': [[5.0, 1.0, 0.0, 0.0, 1.0, 0.0,...","{'Continuous': [[6.0, 1.0, 0.0, 0.0, 1.0, 0.0,...","{'Continuous': [[7.0, 1.0, 0.0, 0.0, 1.0, 0.0,...",NaN
Market,"{'Continuous': [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","{'Continuous': [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","{'Continuous': [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","{'Continuous': [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","{'Continuous': [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","{'Continuous': [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","{'Continuous': [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","{'Continuous': [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...",NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'AlivePlayers': 8, 'PlayerDefeats': 0.0, 'Pro..."

In [10]:
pd.DataFrame(obs[0]['stat'])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
AlivePlayers,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
PlayerDefeats,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Profession,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [11]:
pd.DataFrame(obs[0][0])

,Entity,Tile,Item,Market
Continuous,"[[1.0, 1.0, 0.0, 3.0, 0.0, 0.0, 0.0, 16.0, 24....","[[0.0, 0.0, 9.0, 17.0], [0.0, 0.0, 9.0, 18.0],...","[[0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Discrete,"[[1, 2, 176, 208, 376], [1, 2, 176, 208, 378],...","[[0, 26, 194], [0, 26, 195], [0, 26, 196], [0,...","[[1, 19, 21], [0, 0, 0], [0, 0, 0], [0, 0, 0],...","[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [..."
N,[4],[15],[1],[0]

In [12]:
name_list = {
    "Entity": ["Mask","ID","AttackerID","Level","ItemLevel","Comm","Population","R","C","Damage","TimeAlive","Freeze (deprecated)","Gold","Health","Food","Water","Melee Level","Range Level","Mage Level","Fishing Level","Herbalism Level","Prospecting Level","Carving Level","Alchemy Level"],
    "Tile" : ["NEnts","Index","R","C"],
    "Item" : ["ID","Index","Level","Capacity","Quantity","Tradable","MeleeAttack","RangeAttack","MageAttack","MeleeDefense","RangeDefense","MageDefense","HealthRestore","ResourceRestore","Price","Equipped"],
    "Market" : ["ID","Index","Level","Capacity","Quantity","Tradable","MeleeAttack","RangeAttack","MageAttack","MeleeDefense","RangeDefense","MageDefense","HealthRestore","ResourceRestore","Price","Equipped"],
}

In [13]:
pd.set_option('display.max_columns', None)
df = pd.DataFrame(obs[1][0]["Entity"]["Continuous"])[:7]
df.columns = name_list["Entity"]
df

,Mask,ID,AttackerID,Level,ItemLevel,Comm,Population,R,C,Damage,TimeAlive,Freeze (deprecated),Gold,Health,Food,Water,Melee Level,Range Level,Mage Level,Fishing Level,Herbalism Level,Prospecting Level,Carving Level,Alchemy Level
0,1.0,9.0,0.0,3.0,0.0,0.0,1.0,16.0,56.0,0.0,0.0,0.0,0.0,100.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,1.0,10.0,0.0,3.0,0.0,0.0,1.0,16.0,58.0,0.0,0.0,0.0,0.0,100.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,1.0,11.0,0.0,3.0,0.0,0.0,1.0,16.0,60.0,0.0,0.0,0.0,0.0,100.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,1.0,12.0,0.0,3.0,0.0,0.0,1.0,16.0,62.0,0.0,0.0,0.0,0.0,100.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
pd.set_option('display.max_columns', None)
df = pd.DataFrame(obs[1][0]["Tile"]["Continuous"])
df.columns = name_list["Tile"]
df

     NEnts  Index     R     C
0      0.0    0.0   9.0  49.0
1      0.0    0.0   9.0  50.0
2      0.0    0.0   9.0  51.0
3      0.0    0.0   9.0  52.0
4      0.0    0.0   9.0  53.0
..     ...    ...   ...   ...
220    0.0    5.0  23.0  59.0
221    0.0    5.0  23.0  60.0
222    0.0    4.0  23.0  61.0
223    0.0    2.0  23.0  62.0
224    0.0    2.0  23.0  63.0

[225 rows x 4 columns]

In [15]:
pd.set_option('display.max_columns', None)
df = pd.DataFrame(obs[1][0]["Item"]["Continuous"])[:7]
df.columns = name_list["Item"]
df

,ID,Index,Level,Capacity,Quantity,Tradable,MeleeAttack,RangeAttack,MageAttack,MeleeDefense,RangeDefense,MageDefense,HealthRestore,ResourceRestore,Price,Equipped
0,8.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
pd.set_option('display.max_columns', None)
df = pd.DataFrame(obs[1][0]["Market"]["Continuous"])[:7]
df.columns = name_list["Market"]
df

,ID,Index,Level,Capacity,Quantity,Tradable,MeleeAttack,RangeAttack,MageAttack,MeleeDefense,RangeDefense,MageDefense,HealthRestore,ResourceRestore,Price,Equipped
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0